# Generated by Django 4.0.6 on 2022-07-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quality',
            new_name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('S', 'Smartphone'), ('L', 'Laptop'), ('E', 'Earphone'), ('O', 'Other'), ('TW', 'Top Wear'), ('BW', 'Bottom Wear'), ('AC', 'Accessories'), ('DD', 'Deals_of_day'), ('dd', 'Deals_of_day_second')], max_length=2),
        ),
    ]
